apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: accommodation-facility-consumer
  namespace: {{cookiecutter.k8s_namespace}}
spec:
  schedule: 26 * * * *
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: concept-scores 
            component: accommodation-facility-consumer
        spec:
          serviceAccountName: conceptstream-ksa
          restartPolicy: OnFailure
          containers:
            - name: app
              image: eu.gcr.io/{{cookiecutter.gcp_project_stripped}}-stage/consumer:latest
              imagePullPolicy: Always
              env:
{% raw %}
{{ toYaml .Values.containers.env | indent 14 }}
{% endraw %}
