apiVersion: backstage.io/v1alpha1
kind: template
metadata:
  name: argocd-pipeline
  title: ArgoCD Pipeline
  description:
    Build And Deliver Software on Kubernetes Using Gitops
  tags:
    - recommended
    - argocd
spec:
  owner: hendrik.maus@trivago.com
  templater: cookiecutter
  type: ci/cd
  path: '.'
  schema:
    required:
      - name
      - description
      - gcp_project
      - gcp_region
      - k8s_cluster_name
      - k8s_cluster_project
      - k8s_namespace
    properties:
      component_id:
        title: Name of your application
        type: string
        description: Unique name of the component
      description:
        title: Description of your application
        type: string
        description: Description of the component
      gcp_project:
        title: GCP Project
        type: string
        description: Name of your GCP Project
      gcp_region:
        title: GCP Region
        description: Region in GCP you want to Deploy to
        type: string
        enum:
          - europe-west4
          - us-central1
          - asia-east1
        default: europe-west4
      k8s_cluster_name:
        title: k8s cluster
        description: The cluster you would like to deploy your application to
        type: string
        enum:
          - datproc
          - shared
          - tools
          - build
        default: tools
      k8s_cluster_project:
        title: k8s cluster
        description: The project where the k8s cluster lives
        type: string
        enum:
          - hs-kubernetes
          - shared-kubernetes
        default: shared-kubernetes
      k8s_namespace:
        title: K8s Namespace
        type: string
        description: The k8s namespace you will deploy to in the cluster

