# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/content_synchronised.accommodation.accommodation_feature.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/content_synchronised.accommodation.accommodation_feature.proto',
  package='com.trivago.streaming.toolkit.proto.mysql.accommodation',
  syntax='proto2',
  serialized_options=b'\n7com.trivago.streaming.toolkit.proto.mysql.accommodationB\032accommodation_featureOuterZ7com.trivago.streaming.toolkit.proto.mysql.accommodation',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nBsrc/content_synchronised.accommodation.accommodation_feature.proto\x12\x37\x63om.trivago.streaming.toolkit.proto.mysql.accommodation\"\x84\x02\n\x15\x61\x63\x63ommodation_feature\x12^\n\x03key\x18\x02 \x01(\x0b\x32Q.com.trivago.streaming.toolkit.proto.mysql.accommodation.accommodation_feature.PK\x12\r\n\x05score\x18\x03 \x01(\r\x1a|\n\x02PK\x12\x18\n\x10\x61\x63\x63ommodation_id\x18\x01 \x01(\r\x12\x18\n\x10\x61\x63\x63ommodation_ns\x18\x02 \x01(\r\x12 \n\x18\x61\x63\x63ommodation_feature_id\x18\x03 \x01(\r\x12 \n\x18\x61\x63\x63ommodation_feature_ns\x18\x04 \x01(\rB\x8e\x01\n7com.trivago.streaming.toolkit.proto.mysql.accommodationB\x1a\x61\x63\x63ommodation_featureOuterZ7com.trivago.streaming.toolkit.proto.mysql.accommodation'
)




_ACCOMMODATION_FEATURE_PK = _descriptor.Descriptor(
  name='PK',
  full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.accommodation_feature.PK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accommodation_id', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.accommodation_feature.PK.accommodation_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accommodation_ns', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.accommodation_feature.PK.accommodation_ns', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accommodation_feature_id', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.accommodation_feature.PK.accommodation_feature_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accommodation_feature_ns', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.accommodation_feature.PK.accommodation_feature_ns', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=388,
)

_ACCOMMODATION_FEATURE = _descriptor.Descriptor(
  name='accommodation_feature',
  full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.accommodation_feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.accommodation_feature.key', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.accommodation_feature.score', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ACCOMMODATION_FEATURE_PK, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=388,
)

_ACCOMMODATION_FEATURE_PK.containing_type = _ACCOMMODATION_FEATURE
_ACCOMMODATION_FEATURE.fields_by_name['key'].message_type = _ACCOMMODATION_FEATURE_PK
DESCRIPTOR.message_types_by_name['accommodation_feature'] = _ACCOMMODATION_FEATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

accommodation_feature = _reflection.GeneratedProtocolMessageType('accommodation_feature', (_message.Message,), {

  'PK' : _reflection.GeneratedProtocolMessageType('PK', (_message.Message,), {
    'DESCRIPTOR' : _ACCOMMODATION_FEATURE_PK,
    '__module__' : 'src.content_synchronised.accommodation.accommodation_feature_pb2'
    # @@protoc_insertion_point(class_scope:com.trivago.streaming.toolkit.proto.mysql.accommodation.accommodation_feature.PK)
    })
  ,
  'DESCRIPTOR' : _ACCOMMODATION_FEATURE,
  '__module__' : 'src.content_synchronised.accommodation.accommodation_feature_pb2'
  # @@protoc_insertion_point(class_scope:com.trivago.streaming.toolkit.proto.mysql.accommodation.accommodation_feature)
  })
_sym_db.RegisterMessage(accommodation_feature)
_sym_db.RegisterMessage(accommodation_feature.PK)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
