---
## Add any overrides specific to this env
applications:
  - name: pubsub2kubectl-releases
    namespace: src-conceptscore
    additionalLabels: {}
    additionalAnnotations: {}
    project: src-conceptscore
    source:
      repoURL: git@github.com:trivago/rc5-gcp.git
      targetRevision: master
      path: infrastructure/kubernetes/delivery/manifests/stage-eu-w4/pubsub2kubectl-releases
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: src-conceptscore
    syncPolicy:
      automated: {}

  - name: argo-notifications
    namespace: src-conceptscore
    additionalLabels: {}
    additionalAnnotations: {}
    project: src-conceptscore
    source:
      repoURL: git@github.com:trivago/rc5-gcp.git
      targetRevision: master
      path: infrastructure/kubernetes/delivery/manifests/stage-eu-w4/argo-notifications
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: src-conceptscore
    syncPolicy:
      automated: {}
