apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: producer
  namespace: {{cookiecutter.k8s_namespace}}
spec:
  schedule: 28 * * * *
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{cookiecutter.component_id}}
            component: producer
        spec:
          serviceAccountName: {{cookiecutter.component_id}}-ksa
          restartPolicy: OnFailure
          containers:
            - name: app
              image: eu.gcr.io/{{cookiecutter.gcp_project_stripped}}-stage/producer:latest
              imagePullPolicy: Always
              env:
{% raw %}                
{{ toYaml .Values.containers.env | indent 14 }}
{% endraw %}
