---
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    env:
      - CLOUDBUILDER=v3
      - HELM_VERSION=3.1.2
      - KBLD_VERSION=0.16.0
      - YQ_VERSION=3.3.2
    args:
      - -c
      - |
        docker build --tag gcr.io/$PROJECT_ID/cloudbuilder:$${CLOUDBUILDER} \
          --build-arg HELM_VERSION \
          --build-arg KBLD_VERSION \
          --build-arg YQ_VERSION \
          .

        docker push gcr.io/$PROJECT_ID/cloudbuilder:$${CLOUDBUILDER}
