---
enabled: true
chart: ../charts/service-consumer
namespace: {{cookiecutter.k8s_namespace}}
release_name: src-conceptscore-consumer
output_path: ../manifests
deployments:
  - name: stage-eu-w4
    values:
      - ../values/service-consumer-stage-eu-w4.yaml
  - name: prod-eu-w4
    values:
      - ../values/service-consumer-prod-eu-w4.yaml