# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concept_score.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='concept_score.proto',
  package='com.trivago.streaming.toolkit.proto.mysql.accommodation',
  syntax='proto2',
  serialized_options=b'\n7com.trivago.streaming.toolkit.proto.mysql.accommodationB\022concept_scoreOuterZ7com.trivago.streaming.toolkit.proto.mysql.accommodation',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63oncept_score.proto\x12\x37\x63om.trivago.streaming.toolkit.proto.mysql.accommodation\"\xd8\x01\n\rconcept_score\x12V\n\x03key\x18\x02 \x01(\x0b\x32I.com.trivago.streaming.toolkit.proto.mysql.accommodation.concept_score.PK\x12\r\n\x05score\x18\x03 \x01(\r\x1a`\n\x02PK\x12\x12\n\nconcept_id\x18\x01 \x01(\r\x12\x12\n\nconcept_ns\x18\x02 \x01(\r\x12\x18\n\x10\x61\x63\x63ommodation_id\x18\x03 \x01(\r\x12\x18\n\x10\x61\x63\x63ommodation_ns\x18\x04 \x01(\rB\x86\x01\n7com.trivago.streaming.toolkit.proto.mysql.accommodationB\x12\x63oncept_scoreOuterZ7com.trivago.streaming.toolkit.proto.mysql.accommodation'
)




_CONCEPT_SCORE_PK = _descriptor.Descriptor(
  name='PK',
  full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.concept_score.PK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='concept_id', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.concept_score.PK.concept_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='concept_ns', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.concept_score.PK.concept_ns', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accommodation_id', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.concept_score.PK.accommodation_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accommodation_ns', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.concept_score.PK.accommodation_ns', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=297,
)

_CONCEPT_SCORE = _descriptor.Descriptor(
  name='concept_score',
  full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.concept_score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.concept_score.key', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='com.trivago.streaming.toolkit.proto.mysql.accommodation.concept_score.score', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONCEPT_SCORE_PK, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=297,
)

_CONCEPT_SCORE_PK.containing_type = _CONCEPT_SCORE
_CONCEPT_SCORE.fields_by_name['key'].message_type = _CONCEPT_SCORE_PK
DESCRIPTOR.message_types_by_name['concept_score'] = _CONCEPT_SCORE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

concept_score = _reflection.GeneratedProtocolMessageType('concept_score', (_message.Message,), {

  'PK' : _reflection.GeneratedProtocolMessageType('PK', (_message.Message,), {
    'DESCRIPTOR' : _CONCEPT_SCORE_PK,
    '__module__' : 'concept_score_pb2'
    # @@protoc_insertion_point(class_scope:com.trivago.streaming.toolkit.proto.mysql.accommodation.concept_score.PK)
    })
  ,
  'DESCRIPTOR' : _CONCEPT_SCORE,
  '__module__' : 'concept_score_pb2'
  # @@protoc_insertion_point(class_scope:com.trivago.streaming.toolkit.proto.mysql.accommodation.concept_score)
  })


_sym_db.RegisterMessage(concept_score)
_sym_db.RegisterMessage(concept_score.PK)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)