{% raw %}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "pubsub2kubectl.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pubsub2kubectl.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "pubsub2kubectl.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{% endraw %}
