{% raw %}
---
secret:
  create: true
  notifiers:
    webhooks:
      slack_webhook:
        url: "https://hooks.slack.com/services/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"
        headers:
          - name: content-type
            value: application/json

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi

subscriptions:
  - recipients:
      - webhook:slack_webhook

triggers:
  - name: sync-operation-running
    enabled: true
    condition: app.status.operationState.phase in ['Running']
    template: sync-operation-running

  - name: sync-operation-succeeded
    enabled: true
    condition: app.status.operationState.phase in ['Succeeded']
    template: sync-operation-succeeded

  - name: sync-operation-failed
    enabled: true
    condition: app.status.operationState.phase in ['Error', 'Failed']
    template: sync-operation-failed

  - name: sync-operation-status-unknown
    enabled: true
    condition: app.status.operationState.phase in ['Unknown']
    template: sync-operation-status-unknown

templates:
  - name: sync-operation-running
    webhook:
      slack_webhook:
        method: POST
        body: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":rocket: *{{.app.metadata.name}}* started to sync in *{{.app.metadata.annotations.deploymentName}}*"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*Sync operation details* are available in <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true|Argo CD>"
                  }
                ]
              }
            ]
          }

  - name: sync-operation-succeeded
    webhook:
      slack_webhook:
        method: POST
        body: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":mcheck: *{{.app.metadata.name}}* has been successfully synced in *{{.app.metadata.annotations.deploymentName}}*"
                }
              },{{ if eq .app.metadata.labels.preview "true" }}
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "This is a preview of pull-request <{{.app.metadata.annotations.htmlUrl}}|#{{.app.metadata.annotations.number}}> by {{.app.metadata.annotations.author}}\nDeployed as <http://{{.app.metadata.name}}.your-namespace.edge.europe-west4.nsp.trv.cloud>"
                }
              },{{ end }}
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*Kubernetes* deployment details are available in the <https://console.cloud.google.com/kubernetes/deployment/{{.app.metadata.labels.region}}/{{.app.metadata.annotations.clusterName}}/your-namespace/{{.app.metadata.name}}?organizationId=231382700574&orgonly=true&project=trv-hs-kubernetes-{{.app.metadata.labels.env}}&supportedpurview=organizationId&tab=overview&deployment_overview_active_revisions_tablesize=50&duration=P1D&pod_summary_list_tablesize=20&service_list_datatablesize=20|Cloud Console :gcp: :kubernetes:>"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*Sync operation details* are available in <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true|Argo CD>"
                  }
                ]
              }
            ]
          }

  - name: sync-operation-failed
    webhook:
      slack_webhook:
        method: POST
        body: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":check-no: *{{.app.metadata.name}}* failed sync on *{{.app.metadata.annotations.deploymentName}}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Error at {{.app.status.operationState.finishedAt}}:\n{{.app.status.operationState.message}}"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*Kubernetes* deployment details are available in the <https://console.cloud.google.com/kubernetes/deployment/{{.app.metadata.labels.region}}/{{.app.metadata.annotations.clusterName}}/your-namespace/{{.app.metadata.name}}?organizationId=231382700574&orgonly=true&project=trv-hs-kubernetes-{{.app.metadata.labels.env}}&supportedpurview=organizationId&tab=overview&deployment_overview_active_revisions_tablesize=50&duration=P1D&pod_summary_list_tablesize=20&service_list_datatablesize=20|Cloud Console :gcp: :kubernetes:>"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*Sync operation details* are available in <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true|Argo CD>"
                  }
                ]
              }
            ]
          }

  - name: sync-operation-status-unknown
    webhook:
      slack_webhook:
        method: POST
        body: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":exclamation: *{{.app.metadata.name}}*'s sync status on *{{.app.metadata.annotations.deploymentName}}* is unknown"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*Sync operation details* are available in <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true|Argo CD>"
                  }
                ]
              }
            ]
          }
{% endraw %}
